### PR TITLE
typo fixes and testing new CI

### PR DESCRIPTION
**Pull request by yujiahu415**

### CODE REVIEW

**Review by ruck94301 — COMMENTED** [review]
I've reviewed this PR and have no questions or concerns.

**Comment by yujiahu415** [comment]
Hi John,
After merging your last PR that changes some imports, I filed another PR but failed for the testing. Here's how it failed:

FAILED LabGym/tests/test___main__.py::test_load_duration - ImportError: cannot import name 'img_to_array' from 'keras.preprocessing.image' (D:\a\LabGym\LabGym\.nox\tests-3-10\lib\site-packages\keras\preprocessing\image.py)
FAILED LabGym/tests/test___main__.py::test_main - ImportError: cannot import name 'img_to_array' from 'keras.preprocessing.image' (D:\a\LabGym\LabGym\.nox\tests-3-10\lib\site-packages\keras\preprocessing\image.py)
FAILED LabGym/tests/test___main__.py::test_main_current_labgym - ImportError: cannot import name 'img_to_array' from 'keras.preprocessing.image' (D:\a\LabGym\LabGym\.nox\tests-3-10\lib\site-packages\keras\preprocessing\image.py)
FAILED LabGym/tests/test___main__.py::test_main_stale_labgym - ImportError: cannot import name 'img_to_array' from 'keras.preprocessing.image' (D:\a\LabGym\LabGym\.nox\tests-3-10\lib\site-packages\keras\preprocessing\image.py)
FAILED tests/test_load.py::test_imports_with_sysargv_initialized - ImportError: cannot import name 'img_to_array' from 'keras.preprocessing.image' (D:\a\LabGym\LabGym\.nox\tests-3-10\lib\site-packages\keras\preprocessing\image.py)
FAILED tests/test_load.py::test_remainder - ImportError: cannot import name 'img_to_array' from 'keras.preprocessing.image' (D:\a\LabGym\LabGym\.nox\tests-3-10\lib\site-packages\keras\preprocessing\image.py)
FAILED tests/test_main.py::test_import_gui - ImportError: cannot import name 'img_to_array' from 'keras.preprocessing.image' (D:\a\LabGym\LabGym\.nox\tests-3-10\lib\site-packages\keras\preprocessing\image.py)
7 failed, 25 passed, 2 warnings in 20.67s
nox > Command pytest -q failed with exit code 1
nox > Session tests-3.10 failed.
nox > Ran multiple sessions:
nox > * tests-3.9: failed
nox > * tests-3.10: failed
Error: Process completed with exit code 1.

Can you also take a look at that check? I saw you separate the 'keras' from 'keras.preprocessing.image' in the imports in your PR. Could this be the cause?

Thanks!
Henry
________________________________
